debug: true
server:
  port: 8082
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
      routes:
        - id: biz-provider
          uri: lb://biz-service
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: biz-consumer
          uri: lb://biz-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
#            - RewritePath=/consumer/?(?<segment>.*), /$\{segment}




eureka:
  client:
    service-url:
      defaultZone: http://138.2.232.144:8888/eureka/