logging:
  level:
    com.auyeung.sentinel: debug

spring:
  application:
    name: alibaba-seata-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/seata_test
  sql:
    init:
      schema-locations: classpath*:sql/ddl.sql
      data-locations: classpath*:sql/init.sql
      mode: always
  cloud:
    discovery:
      server-addr: 127.0.0.1:8848
#  cloud:
#    alibaba:
#      seata:
#        application-id: ${spring.application.name}
#        tx-service-group: SEATA_GROUP
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

feign:
  client:
    config:
      default:
        logger-level: full
#  circuitbreaker:
#    enabled: true
  sentinel:
    enabled: true


