server:
  port: 8002
spring:
  sql:
    init:
      schema-locations: classpath:sql/ddl.sql
      mode: always
  application:
    name: alibaba-sentinel-service
  datasource:
    url: jdbc:mysql://172.20.115.2:3306/seata_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    sentinel:
      enabled: false
      transport:
        port: 8719
        dashboard: localhost:8080
    discovery:
      server-addr: 127.0.0.1:8848

