debug: true
server:
  port: 8761
#  EurekaInstanceConfigBean EurekaServerConfigBean EurekaClientConfigBean
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
