server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://138.2.232.144:8888/eureka/
logging:
  level:
    root: debug
    com.auyeung.api: debug
spring:
  application:
    name: biz-consumer
  zipkin:
    base-url: http://192.18.134.94:8848/
    sender:
      type: web
    service:
      name: ${spring.application.name}
#  cloud:
#    circuit:
#      breaker:
#        enabled: true
feign:
#  hystrix:
#    enabled: true
#  sentinel:
#    enabled: true
#  org.springframework.cloud.openfeign.FeignClientsConfiguration 配置
  circuitbreaker:
    enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000