#https://spring-cloud-alibaba-group.github.io/github-pages/2021/en-us/index.html#_spring_cloud_alibaba_rocketmq_binder
spring:
  cloud:
    stream:
      bindings:
        consumeMsg-in-0:
          destination: broadcast
        rocketmq-out-0:
          destination: broadcast
      function:
        definition: consumeMsg
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          enable-msg-trace: true
          customized-trace-topic: RMQ_SYS_TRACE_TOPIC
        bindings:
          consumeMsg-in-0:
            consumer:
              enable: true
              broadcasting: true
              orderly: false
              delayLevelWhenNextConsume: 0
              suspendCurrentQueueTimeMillis: 1000
          rocketmq-out-0:
            producer:
              enable: true
              maxMessageSize: 8249344
              transactional: false
              sync: false
              vipChannelEnabled: true
              sendMessageTimeout: 3000
              compressMessageBodyThreshold: 4096
              retryTimesWhenSendFailed: 2
              retryTimesWhenSendAsyncFailed: 2
              retryNextServer: false