debug: true
logging:
  level:
    root: debug

server:
  port: 8083
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        enabled: true
        git:
          uri: https://github.com/Jasonyang2014/config-repository.git
          username: 305744830@qq.com
          password: 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
          skipSslValidation: true
          default-label: main
#          proxy:
#            https:
#              host: localhost
#              port: 7890
