logging:
  level:
    root: debug
eureka:
  client:
    service-url:
      defaultZone: http://138.2.232.144:8888/eureka/

spring:
  application:
    name: biz-service
  zipkin:
    base-url: http://192.18.134.94:8848/
    sender:
      type: web
    service:
      name: ${spring.application.name}